// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: test.proto

package grpc_testing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A protobuf representation for grpc status. This is used by test
// clients to specify a status that the server should attempt to return.
type EchoStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoStatus) Reset() {
	*x = EchoStatus{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoStatus) ProtoMessage() {}

func (x *EchoStatus) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoStatus.ProtoReflect.Descriptor instead.
func (*EchoStatus) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *EchoStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EchoStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Unary request.
type SimpleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResponseStatus *EchoStatus            `protobuf:"bytes,1,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	User           *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimpleRequest) Reset() {
	*x = SimpleRequest{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRequest) ProtoMessage() {}

func (x *SimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRequest.ProtoReflect.Descriptor instead.
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *SimpleRequest) GetResponseStatus() *EchoStatus {
	if x != nil {
		return x.ResponseStatus
	}
	return nil
}

func (x *SimpleRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Dummy request with a fieldmask
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Dummy response with a fieldmask
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Unary response, as configured by the request.
type SimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *SimpleResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SimpleAnyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserProps     *anypb.Any             `protobuf:"bytes,2,opt,name=user_props,json=userProps,proto3" json:"user_props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleAnyRequest) Reset() {
	*x = SimpleAnyRequest{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleAnyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleAnyRequest) ProtoMessage() {}

func (x *SimpleAnyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleAnyRequest.ProtoReflect.Descriptor instead.
func (*SimpleAnyRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *SimpleAnyRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SimpleAnyRequest) GetUserProps() *anypb.Any {
	if x != nil {
		return x.UserProps
	}
	return nil
}

type SimpleAnyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserProps     *anypb.Any             `protobuf:"bytes,2,opt,name=user_props,json=userProps,proto3" json:"user_props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleAnyResponse) Reset() {
	*x = SimpleAnyResponse{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleAnyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleAnyResponse) ProtoMessage() {}

func (x *SimpleAnyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleAnyResponse.ProtoReflect.Descriptor instead.
func (*SimpleAnyResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *SimpleAnyResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SimpleAnyResponse) GetUserProps() *anypb.Any {
	if x != nil {
		return x.UserProps
	}
	return nil
}

// Client-streaming request.
type StreamingInputCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingInputCallRequest) Reset() {
	*x = StreamingInputCallRequest{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingInputCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingInputCallRequest) ProtoMessage() {}

func (x *StreamingInputCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingInputCallRequest.ProtoReflect.Descriptor instead.
func (*StreamingInputCallRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *StreamingInputCallRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Client-streaming response.
type StreamingInputCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregated size of payloads received from the client.
	AggregatedPayloadSize int32 `protobuf:"varint,1,opt,name=aggregated_payload_size,json=aggregatedPayloadSize,proto3" json:"aggregated_payload_size,omitempty"`
	User                  *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StreamingInputCallResponse) Reset() {
	*x = StreamingInputCallResponse{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingInputCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingInputCallResponse) ProtoMessage() {}

func (x *StreamingInputCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingInputCallResponse.ProtoReflect.Descriptor instead.
func (*StreamingInputCallResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *StreamingInputCallResponse) GetAggregatedPayloadSize() int32 {
	if x != nil {
		return x.AggregatedPayloadSize
	}
	return 0
}

func (x *StreamingInputCallResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Configuration for a particular response.
type ResponseParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Desired payload sizes in responses from the server.
	// If response_type is COMPRESSABLE, this denotes the size before compression.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Desired interval between consecutive responses in the response stream in
	// microseconds.
	IntervalUs    int32 `protobuf:"varint,2,opt,name=interval_us,json=intervalUs,proto3" json:"interval_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseParameters) Reset() {
	*x = ResponseParameters{}
	mi := &file_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseParameters) ProtoMessage() {}

func (x *ResponseParameters) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseParameters.ProtoReflect.Descriptor instead.
func (*ResponseParameters) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseParameters) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ResponseParameters) GetIntervalUs() int32 {
	if x != nil {
		return x.IntervalUs
	}
	return 0
}

// Server-streaming request.
type StreamingOutputCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration for each expected response message.
	ResponseParameters []*ResponseParameters `protobuf:"bytes,1,rep,name=response_parameters,json=responseParameters,proto3" json:"response_parameters,omitempty"`
	// Optional input payload sent along with the request.
	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Whether server should return a given status
	ResponseStatus *EchoStatus `protobuf:"bytes,3,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamingOutputCallRequest) Reset() {
	*x = StreamingOutputCallRequest{}
	mi := &file_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingOutputCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingOutputCallRequest) ProtoMessage() {}

func (x *StreamingOutputCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingOutputCallRequest.ProtoReflect.Descriptor instead.
func (*StreamingOutputCallRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{11}
}

func (x *StreamingOutputCallRequest) GetResponseParameters() []*ResponseParameters {
	if x != nil {
		return x.ResponseParameters
	}
	return nil
}

func (x *StreamingOutputCallRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *StreamingOutputCallRequest) GetResponseStatus() *EchoStatus {
	if x != nil {
		return x.ResponseStatus
	}
	return nil
}

// Server-streaming response, as configured by the request and parameters.
type StreamingOutputCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payload to increase response size.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingOutputCallResponse) Reset() {
	*x = StreamingOutputCallResponse{}
	mi := &file_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingOutputCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingOutputCallResponse) ProtoMessage() {}

func (x *StreamingOutputCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingOutputCallResponse.ProtoReflect.Descriptor instead.
func (*StreamingOutputCallResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{12}
}

func (x *StreamingOutputCallResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x17grpc_client_cli.testing\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/field_mask.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\":\n" +
	"\n" +
	"EchoStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x01\n" +
	"\rSimpleRequest\x12L\n" +
	"\x0fresponse_status\x18\x01 \x01(\v2#.grpc_client_cli.testing.EchoStatusR\x0eresponseStatus\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.grpc_client_cli.testing.UserR\x04user\"L\n" +
	"\rUpdateRequest\x12;\n" +
	"\vupdate_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"M\n" +
	"\x0eUpdateResponse\x12;\n" +
	"\vupdate_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"C\n" +
	"\x0eSimpleResponse\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.grpc_client_cli.testing.UserR\x04user\"`\n" +
	"\x10SimpleAnyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x123\n" +
	"\n" +
	"user_props\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\tuserProps\"a\n" +
	"\x11SimpleAnyResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x123\n" +
	"\n" +
	"user_props\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\tuserProps\"N\n" +
	"\x19StreamingInputCallRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.grpc_client_cli.testing.UserR\x04user\"\x87\x01\n" +
	"\x1aStreamingInputCallResponse\x126\n" +
	"\x17aggregated_payload_size\x18\x01 \x01(\x05R\x15aggregatedPayloadSize\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.grpc_client_cli.testing.UserR\x04user\"I\n" +
	"\x12ResponseParameters\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x1f\n" +
	"\vinterval_us\x18\x02 \x01(\x05R\n" +
	"intervalUs\"\xfb\x01\n" +
	"\x1aStreamingOutputCallRequest\x12\\\n" +
	"\x13response_parameters\x18\x01 \x03(\v2+.grpc_client_cli.testing.ResponseParametersR\x12responseParameters\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.grpc_client_cli.testing.UserR\x04user\x12L\n" +
	"\x0fresponse_status\x18\x03 \x01(\v2#.grpc_client_cli.testing.EchoStatusR\x0eresponseStatus\"P\n" +
	"\x1bStreamingOutputCallResponse\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.grpc_client_cli.testing.UserR\x04user2\xf7\x06\n" +
	"\vTestService\x12;\n" +
	"\tEmptyCall\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\tUnaryCall\x12&.grpc_client_cli.testing.SimpleRequest\x1a'.grpc_client_cli.testing.SimpleResponse\x12b\n" +
	"\x0fUnaryUpdateCall\x12&.grpc_client_cli.testing.UpdateRequest\x1a'.grpc_client_cli.testing.UpdateResponse\x12\x82\x01\n" +
	"\x13StreamingOutputCall\x123.grpc_client_cli.testing.StreamingOutputCallRequest\x1a4.grpc_client_cli.testing.StreamingOutputCallResponse0\x01\x12\x7f\n" +
	"\x12StreamingInputCall\x122.grpc_client_cli.testing.StreamingInputCallRequest\x1a3.grpc_client_cli.testing.StreamingInputCallResponse(\x01\x12\x7f\n" +
	"\x0eFullDuplexCall\x123.grpc_client_cli.testing.StreamingOutputCallRequest\x1a4.grpc_client_cli.testing.StreamingOutputCallResponse(\x010\x01\x12\x7f\n" +
	"\x0eHalfDuplexCall\x123.grpc_client_cli.testing.StreamingOutputCallRequest\x1a4.grpc_client_cli.testing.StreamingOutputCallResponse(\x010\x01\x12a\n" +
	"\bUnaryAny\x12).grpc_client_cli.testing.SimpleAnyRequest\x1a*.grpc_client_cli.testing.SimpleAnyResponseB\x10Z\x0e/;grpc_testingb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_test_proto_goTypes = []any{
	(*User)(nil),                        // 0: grpc_client_cli.testing.User
	(*EchoStatus)(nil),                  // 1: grpc_client_cli.testing.EchoStatus
	(*SimpleRequest)(nil),               // 2: grpc_client_cli.testing.SimpleRequest
	(*UpdateRequest)(nil),               // 3: grpc_client_cli.testing.UpdateRequest
	(*UpdateResponse)(nil),              // 4: grpc_client_cli.testing.UpdateResponse
	(*SimpleResponse)(nil),              // 5: grpc_client_cli.testing.SimpleResponse
	(*SimpleAnyRequest)(nil),            // 6: grpc_client_cli.testing.SimpleAnyRequest
	(*SimpleAnyResponse)(nil),           // 7: grpc_client_cli.testing.SimpleAnyResponse
	(*StreamingInputCallRequest)(nil),   // 8: grpc_client_cli.testing.StreamingInputCallRequest
	(*StreamingInputCallResponse)(nil),  // 9: grpc_client_cli.testing.StreamingInputCallResponse
	(*ResponseParameters)(nil),          // 10: grpc_client_cli.testing.ResponseParameters
	(*StreamingOutputCallRequest)(nil),  // 11: grpc_client_cli.testing.StreamingOutputCallRequest
	(*StreamingOutputCallResponse)(nil), // 12: grpc_client_cli.testing.StreamingOutputCallResponse
	(*fieldmaskpb.FieldMask)(nil),       // 13: google.protobuf.FieldMask
	(*anypb.Any)(nil),                   // 14: google.protobuf.Any
	(*emptypb.Empty)(nil),               // 15: google.protobuf.Empty
}
var file_test_proto_depIdxs = []int32{
	1,  // 0: grpc_client_cli.testing.SimpleRequest.response_status:type_name -> grpc_client_cli.testing.EchoStatus
	0,  // 1: grpc_client_cli.testing.SimpleRequest.user:type_name -> grpc_client_cli.testing.User
	13, // 2: grpc_client_cli.testing.UpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	13, // 3: grpc_client_cli.testing.UpdateResponse.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 4: grpc_client_cli.testing.SimpleResponse.user:type_name -> grpc_client_cli.testing.User
	14, // 5: grpc_client_cli.testing.SimpleAnyRequest.user_props:type_name -> google.protobuf.Any
	14, // 6: grpc_client_cli.testing.SimpleAnyResponse.user_props:type_name -> google.protobuf.Any
	0,  // 7: grpc_client_cli.testing.StreamingInputCallRequest.user:type_name -> grpc_client_cli.testing.User
	0,  // 8: grpc_client_cli.testing.StreamingInputCallResponse.user:type_name -> grpc_client_cli.testing.User
	10, // 9: grpc_client_cli.testing.StreamingOutputCallRequest.response_parameters:type_name -> grpc_client_cli.testing.ResponseParameters
	0,  // 10: grpc_client_cli.testing.StreamingOutputCallRequest.user:type_name -> grpc_client_cli.testing.User
	1,  // 11: grpc_client_cli.testing.StreamingOutputCallRequest.response_status:type_name -> grpc_client_cli.testing.EchoStatus
	0,  // 12: grpc_client_cli.testing.StreamingOutputCallResponse.user:type_name -> grpc_client_cli.testing.User
	15, // 13: grpc_client_cli.testing.TestService.EmptyCall:input_type -> google.protobuf.Empty
	2,  // 14: grpc_client_cli.testing.TestService.UnaryCall:input_type -> grpc_client_cli.testing.SimpleRequest
	3,  // 15: grpc_client_cli.testing.TestService.UnaryUpdateCall:input_type -> grpc_client_cli.testing.UpdateRequest
	11, // 16: grpc_client_cli.testing.TestService.StreamingOutputCall:input_type -> grpc_client_cli.testing.StreamingOutputCallRequest
	8,  // 17: grpc_client_cli.testing.TestService.StreamingInputCall:input_type -> grpc_client_cli.testing.StreamingInputCallRequest
	11, // 18: grpc_client_cli.testing.TestService.FullDuplexCall:input_type -> grpc_client_cli.testing.StreamingOutputCallRequest
	11, // 19: grpc_client_cli.testing.TestService.HalfDuplexCall:input_type -> grpc_client_cli.testing.StreamingOutputCallRequest
	6,  // 20: grpc_client_cli.testing.TestService.UnaryAny:input_type -> grpc_client_cli.testing.SimpleAnyRequest
	15, // 21: grpc_client_cli.testing.TestService.EmptyCall:output_type -> google.protobuf.Empty
	5,  // 22: grpc_client_cli.testing.TestService.UnaryCall:output_type -> grpc_client_cli.testing.SimpleResponse
	4,  // 23: grpc_client_cli.testing.TestService.UnaryUpdateCall:output_type -> grpc_client_cli.testing.UpdateResponse
	12, // 24: grpc_client_cli.testing.TestService.StreamingOutputCall:output_type -> grpc_client_cli.testing.StreamingOutputCallResponse
	9,  // 25: grpc_client_cli.testing.TestService.StreamingInputCall:output_type -> grpc_client_cli.testing.StreamingInputCallResponse
	12, // 26: grpc_client_cli.testing.TestService.FullDuplexCall:output_type -> grpc_client_cli.testing.StreamingOutputCallResponse
	12, // 27: grpc_client_cli.testing.TestService.HalfDuplexCall:output_type -> grpc_client_cli.testing.StreamingOutputCallResponse
	7,  // 28: grpc_client_cli.testing.TestService.UnaryAny:output_type -> grpc_client_cli.testing.SimpleAnyResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
