name: build

on:
  push:
    branches:
      - main
      - "feature/**"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'

      - name: test
        run: |
          export GOTESTSUM_VERSION=1.12.0
          curl -L https://github.com/gotestyourself/gotestsum/releases/download/v${GOTESTSUM_VERSION}/gotestsum_${GOTESTSUM_VERSION}_linux_amd64.tar.gz | sudo tar -C /usr/local/bin -xz
          gotestsum --format short-verbose --no-summary=skipped ./...

      - name: build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: --skip=publish,validate --clean --snapshot

      - name: prepare dist directory
        run: |
          find ./dist/ -not -name '*.tar.gz' -not -name '*.zip' -not -name 'dist' -delete

      - name: store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: prep
        id: prep
        run: |
          ls -R
          find . -name "grpc-client-cli*" -type f -exec chmod +x {} \;
          echo "tags=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "grpc-client-cli*"
          tag: ${{ github.ref }}
          name: ${{ steps.prep.outputs.tags }}
          body: |
            v${{ steps.prep.outputs.tags }}
          draft: false
          prerelease: true
